apiVersion: v1
kind: Service                   
metadata:
    name: pst-nodeport-service   
spec:
    type: NodePort                 # A port is opened on each node in your cluster via Kube proxy.
    ports:                         # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
    - name: http
      port: 8083                   # port on the service
      targetPort: 8083             # port on the pod
      nodePort: 30007              # port on the node
    selector:
        app: pst-current-time         # Map any pod with label `app=pst-current-time` to this service